"posix=1;\n"
"for cmd in echo chgrp chmod chown cut dd df expr ln ls mkdir mv rm read rmdir tee test touch wc; do\n"
"	type $cmd >/dev/null 2>&1 || posix=0;\n"
"done;\n"
"if test $posix = 1; then\n"
"	echo \"ok stable\";\n"
"else\n"
"	echo failed;\n"
"fi;\n"
